services:
  - type: web
    name: homelyhub-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 8000
      - key: ORIGIN_ACCESS_URL
        value: https://homely-hub123.netlify.app
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: JWT_COOKIE_EXPIRES_IN
        value: 90
